### ISSUE TITLE
Investigate JSON-LD instead of microdata for Schema.org values

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-default-theme#81]
See discussion here: http://forum.textpattern.com/viewtopic.php?id=47366

Whilst my personal preference is still Schema.org microdata, I'm testing out JSON-LD as a possible replacement. Pros/cons of the change:

1. Pro: Google's Structured Data Testing Tool has become way too opinionated on what microdata is mandatory - leading to overly-complex HTML. They also break the spec and contradict Schema.org documentation on numerous occasions (e.g. publisher cannot be a Person on Google Testing Tool, but is allowed in Schema.org documentation).
2. Con: JSON-LD shares the above problem - so it won't lead to a reduction in code (in fact it leads to generally more code as you can't have multiple entry points in JSON, and also duplicates content already in the HTML).
3. Pro: Google has done a complete 180 and now recommends JSON-LD over microdata (they used to favour vice-versa).
4. Con: microdata is more human-readable than JSON-LD.
5. Pro: I can create a `misc`-type Form template to power JSON-LD in the page `head`.
6. Con: if you add in more images and/or file downloads via additional forms, we'll have to include additional JavaScript in the `body` of the page ad-hoc. More code bloat compared to HTML attributes (and not as tidy as I'd like - I'd prefer to house all JSON-LD in `head`, but that is impossible here).

Example JSON-LD for a blog individual article:

    <script type="application/ld+json">
        {
            "@context": "http://schema.org",
            "@graph": [
                {
                    "@type": "Blog",
                    "blogPost": [
                        {
                            "@type": "BlogPosting",
                            "headline": "Blog example title",
                            "description": "This is where a blog article extract/description would be.",
                            "url": "http://textpattern.dev/blog-article.html",
                            "mainEntityOfPage": "http://textpattern.dev/blog-article.html",
                            "datePublished": "2016-01-21T10:43:39Z",
                            "dateModified": "2016-01-22T14:32:01Z",
                            "discussionUrl": "http://textpattern.dev/blog-article.html#comments-head",
                            "image": {
                                "@type": "ImageObject",
                                "url": "http://placehold.it/832x554",
                                "width": "832",
                                "height": "554"
                            },
                            "author": {
                                "@type": "Person",
                                "name": "Phil Wareham"
                            },
                            "publisher": {
                                "@type": "Organization",
                                "name": "Textpattern CMS",
                                "logo": {
                                    "@type": "ImageObject",
                                    "url": "http://textpattern.com/assets/img/branding/textpattern/textpattern.png",
                                    "width": "320",
                                    "height": "52"
                                }
                            },
                            "interactionStatistic": {
                                "@type": "InteractionCounter",
                                "interactionType": "http://schema.org/CommentAction",
                                "userInteractionCount": "3"
                            },
                            "comment": [
                                {
                                    "@type": "Comment",
                                    "author": {
                                        "@type": "Person",
                                        "name": "Joe Q. Public"
                                    },
                                    "dateCreated": "2016-01-25T16:55:03Z"
                                },
                                {
                                    "@type": "Comment",
                                    "author": {
                                        "@type": "Person",
                                        "name": "Phil Wareham"
                                    },
                                    "dateCreated": "2016-01-26T11:20:01Z"
                                }
                            ]
                        }
                    ]
                },
                {
                    "@type": "WebSite",
                    "name": "Textpattern CMS",
                    "description": "Textpattern CMS is a free, open source content management system with a browser-based interface in over 40 languages, excellent support and full range of features.",
                    "url": "http://textpattern.dev/",
                    "potentialAction": {
                        "@type": "SearchAction",
                        "target": "http://textpattern.dev/?q={q}",
                        "query-input": "required name=q"
                    }
                },
                {
                    "@type": "Organization",
                    "name": "Textpattern CMS",
                    "url": "http://textpattern.dev/",
                    "logo": "http://textpattern.com/assets/img/branding/textpattern/textpattern.png"
                }
            ]
        }
    </script>

**Comment by jools-r** [comment]
Interesting. A lot of the page description details in your example are (often) already provided in the xml sitemap or feed, and even already in the head markup itself. Images and files can also be specified in the sitemap, but that's hard to do in txp if images and downloads are specified inline in the txp:body and not extractable via the image-article field or a custom-field.

How does using JSON-LD work with all the inline schema.org microdata you provide in the markup denoting the purpose of page areas and specific bits of page content. I can't see how you could predict everything on the page to summarise it in the html head. I already find the current microdata pretty wordy. With JSON-LD would you need to have a running commentary of parallel inline `<script>… JSON-LD …</script>` tags describing the markup as it appears?

**Comment by philwareham** [comment]
@jools-r JSON-LD would pretty much replace HTML microdata, although the more I use it the less keen I am on it. You are effectively duplicating all your content again in JSON-LD just so you can describe it - which looks crazy to me. I haven't even put `articleBody` or comment `text` in the above JSON-LD example.

Of course, the above example is fairly in-depth. Another solution would be to scale back all HTML microdata (or JSON-LD) to the bare requirements (i.e. stop describing things such as comments, interactionStatistic etc.). That seems a shame (as you are doing half a job) not describing certain content - but might be the right solution for a theme.

**Comment by philwareham** [comment]
Just for the record, the bare minimum mandatory entries for a `BlogPosting` (or `Article`) in JSON-LD according to Google Structured Data Testing Tool are:

    "headline"
    "description" (optional but recommended)
    "url"
    "mainEntityOfPage" (optional but recommended)
    "datePublished"
    "dateModified" (optional but recommended)
    "image" (plus attributes)
    "author" (plus attributes)
    "publisher" (plus attributes - can't be a person)

Source: https://developers.google.com/search/docs/data-types/articles

Not sure what the SEO implications are of not including `articleBody` too - might harm SEO but might not.

**Comment by jools-r** [comment]
Sorry @philwareham, but I edited my above post to include more info. It sounds like we agree.

My general feeling (probably unqualified) is that the HTML5 markup already describes a fair amount of information, particularly with regard to page regions and purposes, and that additional microdata is useful to denote specific markup that is otherwise not readily identifiable, such as event details, contact details, book sources, film times, property details and so on and so forth. When microdata goes as far as describing exactly what the markup already describes, it seems redundant (to me at least) - and, as you say, duplicating the entire content seems crazy.

Maybe that is stuff for a tutorial for specific cases where providing specific microdata where portability is very desirable – e.g. a property/real-estate listing – and such information is already stored in the CMS at a sufficiently granular level.

I agree with your theme comment too: your basic template is brilliant as a learning example for textpattern and how it works. The microdata offers a good starting point, but it also clouds the learning experience, making the code look more complex at first glance than it really is.

**Comment by Bloke** [comment]
I don't really see the benefit either. Presumably, the need to define a region that has already been suitably defined in an HTML tag is to make it _more specific_ and give it greater context. e.g. a `<section>` is generic but a `<section>` further defined as a 'comment' gives it more semantic meaning.

Quite why the bare minimum includes things that can easily and unambiguously be defined in HTML (e.g. image) is a mystery. Unless they mean 'main image' or something.

**Comment by philwareham** [comment]
@Bloke in this context it's an image associated directly with the article as opposed to general images on the page - although by containing the image within an `<article>` tag I'd think that would already be associated with the article in question (also, not all articles need an image so it's annoying that one is required here).

My gut feeling is to leave the HTML microdata in place and not implement JSON-LD at this point in time. Google only 'recommend' JSON-LD as it's easier to add to an existing site - there's no penalty for using HTML microdata instead.

**Comment by wion** [comment]
Just to provide a little backstory to the original post in the forum...

I was working on (still am, but currently on ice) a glossary project, and was looking at making the definition articles semantic. The who glossary would be a separate domain (e.g. glossary.csf.community), so the whole thing would be like a glossary mini site. An individual definition page page would have several unique regions and nested type elements to semantically label. Some of the idea are borrowed from an academic article, actually, and there are some resources for that online, which I don't have handy at the moment.

Anyway, as started looking at the three types -- the two markup types (microdata and RDFa) and the header/JavaScript type (JSON-LD), I began to realize a couple of things:

1. Of the two markup types, RDFa was generally less verbose, especially if you were using more than one vocabulary source (e.g. scheme.org, Dublin Core, etc).
2. The markup types had to be added as attributes in the HTML, while JSON-LD was (as it seemed to me at the time) all in one place in a single external file.

Inclined to producing concise code, and knowing that the future of dynamic CMSes is to chunk content/markup into many little boxes (e.g. Txp forms), I first favored RDFA over microdata, but then began to think it could be hard to visually all the scoped attributes of RDFa or a given document when the document is parsed into many different fields and chunk types. JSON-LD seemed like a better choice in that latter case; all medata in one file and nothing in the HTML markup.

That's when I thought to make the post in the forum. I figured maybe nobody had considered JSON-LD before as a way to make the HTML cleaner. I had no idea there would be technical hurdles. Other PHP systems seem to use it, so I figured Txp could too.

Beyond that I'm not hell bent on JSON-LD, especially if it's more trouble than it's worth. But my impression from what's going on in other circles is that it's the future as far as metadata goes. Though I don't rely solely on what Google says. There are other search engines in the world. And on a personal level, I prefer RDFa over microdata because attributes are less verbose.

I can back-whip myself to replace default microdata and add my own RDFa. I just offered the thought of JSON-LD in case there was something useful there as a way to make markup cleaner (no extra metadata attributes at all, especially when you consider there could be ARIA attributes too). Likewise, not have to have some complicated mental map of how all the content/HTML chunks fit together across templates, forms, custom fields, and/or whatever blocks that fit a document together, in the event you have to edit your metadata.

**Comment by philwareham** [comment]
@wion I can see uses for JSON-LD - such as provide a data stream that can harnessed by apps, AMP pages, Google rich snippets. But for the default theme not sure it's a good route. Will continue keeping an eye on developments.

**Comment by steverowling** [comment]
@philwareham If it's of interest, take a look at the [SEOMatic plugin for CraftCMS](https://github.com/nystudio107/seomatic/wiki). It's a very comprehensive implementation of JSON-LD (plus Facebook OG and Twitter Cards) that sets up default value for everything in a settings area, then allows for different levels of overrides at template and entry level. It also includes a really useful keyword analysis tool and can handle Google Analytics for a site too. Well worth a look if you are interested in seeing other implementations.

**Comment by philwareham** [comment]
I've implemented JSON-LD in a few Textpattern sites but I feel it's too complex/overarching for the default theme when compared to microformats. Closing.

If you want a demo of JSON-LD code see: https://github.com/textpattern/textpattern-com-website/blob/master/src/templates/pages/blog.txp
